version: '3'
services:
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.9.1
    user: root
    networks:
      elasticsearch_vpc:
        ipv4_address: 192.168.168.19
    container_name: filebeat-192.168.168.19
    volumes:
      - "./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro"
      - "/root/logs:/usr/share/filebeat/logs:ro"
    environment:
      - ELASTICSEARCH_HOST=http://192.168.168.18:9200
      - KIBANA_HOST=http://192.168.168.240:5601/kibana

networks:
  elasticsearch_vpc:
    external: true
    name: vpc_network