version: '3'
services:
  init-elasticsearch:
    image: ubuntu:20.04
    user: root
    networks:
      elasticsearch_vpc:
        ipv4_address: 192.168.168.17
    container_name: init-elasticsearch
    volumes:
      - /data/cr-volumns/elasticsearch/data:/usr/share/elasticsearch/data
    command: ["/bin/bash", "-c", "chown 1000:1000 /usr/share/elasticsearch/data -R"]

  elasticsearch:
    image: cr.svc.ltd/elasticsearch:7.12.0
    networks:
      elasticsearch_vpc:
        ipv4_address: 192.168.168.18
    container_name: elasticsearch-192.168.168.18
    volumes:
      - /data/cr-volumns/elasticsearch/data:/usr/share/elasticsearch/data
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    restart: always
    depends_on:
      init-elasticsearch:
          condition: service_completed_successfully
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: -Xms4096m -Xmx4096m

networks:
  elasticsearch_vpc:
    external: true
    name: vpc_network