version: '3'
services:
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "8080:80"

    dns:
      - 8.8.8.8
      - 4.4.4.4
      
    volumes:
      - ./conf.d:/etc/nginx/conf.d
